### ISSUE TITLE
能否添加浏览器选择使用chrome或者ie的功能

### ISSUE THREAD

**Issue by GoRoad** [RecluseXU/CheckStrackerLoader#1]
在使用此软件初始化ie登录n网会出现Invalid Login or password.提示，但账号密码是正确的

**Comment by RecluseXU** [comment]
实际上，IE是万不得已的选择。
selenium的chrome webdirver几乎一个版本一个，而各个浏览器使用的chrome内核版本各有不同。
由于我无法获取他们用的浏览器实际上用的是什么内核，所以chrome能否启动就像一个运气游戏一样。
如果你知道你的版本，你可以去这里 http://npm.taobao.org/mirrors/chromedriver/
去下载webdriver替换lib目录下的对应项。
这样就能正常启动chrome了。

**Comment by RecluseXU** [comment]
IE的问题我尝试修复了一下，暂时不知道效果。

**Comment by GoRoad** [comment]
Chrome可以直接使用最新版的，因为Chrome的更新在国内是可以直接进行的，国产浏览器需要单独指定版本

**Comment by RecluseXU** [comment]
确实
